### PR TITLE
Update MCV Market for new factions

### PR DESCRIPTION
**Pull request by Icephoenix2019**

### CODE REVIEW

**Comment by hunterczech** [comment]
Crash upon opening MCV Market - Exception of type `System.InvalidOperationException`: Unit `mmsowmcv` does not have any sequences defined.

**Comment by Icephenoix2019** [comment]
Yeah I forgot to do `Rendersprite` for SOW MCV, I will add that in later

**Comment by hunterczech** [comment]
No need for that. I fixed it in my builds simply by making mmsowmcv sequence that inherits sow_mcv

**Comment by Icephenoix2019** [comment]
I see, I still did `Rendersprite` just in case :)

**Comment by Icephenoix2019** [comment]
Also I might have to add the condition of mmsow to sow.yaml

**Pull request closed without merging**
